### ISSUE TITLE
Can't create table `cart_items` "Foreign key constraint is incorrectly formed"

### ISSUE THREAD

**Issue by mohamed-ea** [Matildevoldsen/Filament-CMS-YT#1]
Hello,

I was trying your project bit got an error while running migrate commande:
`  SQLSTATE[HY000]: General error: 1005 Can't create table `yt-cms-flm`.`cart_items` (errno: 150 "Foreign key constraint is incorrectly formed") (Connection: mysql, SQL: alter table `cart_items` add constraint `cart_items_variant_id_foreign` foreign key (`variant_id`) references `product_variations` (`id`) on delete cascade)
`  
 It make sense as the **product-variations** is not created yet, i just changed the order to make this migration after the one that create **product_variations** table and it worked.

**Comment by alisalehi1380** [comment]
@Matildevoldsen  any suggestions?

**Comment by alisalehi1380** [comment]
@mohamed-ea 👍🔥
